# Generated by Django 4.1 on 2023-07-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hod", models.TextField(default="1")),
                ("temperature", models.TextField(default="0")),
                ("humidity", models.TextField(default="10")),
                ("leafwetness", models.TextField(default="0")),
                ("rain", models.TextField(default="0")),
                ("GS", models.TextField(default="0")),
                ("treatment", models.BooleanField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LotId", models.TextField(default="000000")),
                ("year", models.TextField(default="2000")),
                ("doy", models.TextField(default="1")),
                ("ASCmat_t0", models.TextField(default="0")),
                ("COMmat_t0", models.TextField(default="0")),
                ("H_post_t0", models.TextField(default="0")),
                ("H_rain_t0", models.TextField(default="0")),
                ("Hdry_t0", models.TextField(default="0")),
                ("RH_t0", models.TextField(default="0")),
                ("wetness_t0", models.TextField(default="0")),
                ("WD_t0", models.TextField(default="0")),
                ("SEV_asco_t0", models.TextField(default="0")),
                ("SEV_con_t0", models.TextField(default="0")),
                ("ONS_t0", models.TextField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LotId", models.TextField(default="000000")),
                ("year", models.TextField(default="2000")),
                ("doy", models.TextField(default="1")),
                (
                    "daily",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blackrot.daily"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blackrot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blackrot.data"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blackrot.state"
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
