# Generated by Django 4.1 on 2023-07-11 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blackrot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state",
            old_name="H_post_t0",
            new_name="H_postr_t0",
        ),
    ]
