# Generated by Django 4.2.5 on 2023-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blackrot", "0004_state_dd_10_t0_state_dd_6_24_t0_state_dd_9_25_t0"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="h4_rain_t0",
            field=models.FloatField(default=0),
        ),
    ]
